### PR TITLE
logging return value of writev(2)

### PR DESCRIPTION
**Pull request by karupanerura**

### CODE REVIEW

**Comment by syohex** [comment]
There is similar part at https://github.com/karupanerura/Gazelle/blob/logging-writev-rv/lib/Plack/Handler/Gazelle.xs#L1040 

And return value of `writev` in error case is always `-1`(See [manpage](http://pubs.opengroup.org/onlinepubs/009695399/functions/write.html)). So it makes little sense. I suppose `errno` or `strerror`(`strerror_r`) is better than return value.

**Comment by karupanerura** [comment]
> And return value of writev in error case is always -1
Yes. I know that. But, this case is `if ( rv <= 0 )`.  So I want to know the `rv` value is zero or not.

**Comment by syohex** [comment]
Ah sorry, I missed.

**Comment by karupanerura** [comment]
> There is similar part at https://github.com/karupanerura/Gazelle/blob/logging-writev-rv/lib/Plack/Handler/Gazelle.xs#L1040

**Comment by karupanerura** [comment]
NOTE: Tests failed at travis-ci. but it works. Are travis-ci broekn? (maybe)
https://travis-ci.org/kazeburo/Gazelle/jobs/113327668

**Comment by syohex** [comment]
There were network issue(sometimes error happens :-()  and not related to this change. Please retry tests by `git commit --amend`(no changes), `git push -f` or asking repository owner.

BTW: it is better to set `sudo: false` in `.travis.yml` for faster CI.

**Comment by karupanerura** [comment]
@kazeburo will you merge it?

**Comment by kazeburo** [comment]
https://travis-ci.org/kazeburo/Gazelle/jobs/113327667
test passed

**Comment by karupanerura** [comment]
thank you!

**Pull request merged**
